### ISSUE TITLE
make install fails if mpstool is not installed

### ISSUE THREAD

**Issue by pjuda** [UniNE-CHYN/mps_toolbox#15]
If you run `pip3 uninstall -y mpstool` without mpstool installed, the following error occurs:
```
Cannot uninstall requirement mpstool, not installed
You are using pip version 8.1.1, however version 19.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
makefile:2: recipe for target 'install' failed
make: *** [install] Error 1
```

To reproduce, uninstall mpstool `pip3 uninstall -y mpstool` and run `make install` in the project root directory.

**Comment by GCoiffier** [comment]
I am not able to reproduce the error. I thought the -y flag was there to ignore the step if `mpstool` was not found.

Anyway, I modified the command so that `make install` runs with the `-U` flag and does not try to uninstall the package beforehand. The pull request #16 has been submitted.

We should also see if we are able to host the library somewhere, so it can be downloaded via pip without cloning this repository

**Comment by pjuda** [comment]
> We should also see if we are able to host the library somewhere, so it can be downloaded via pip without cloning this repository

Good comment. We have been discussing with @philipperenard and @julien-straubhaar the possibility to further merge mpstool with Julien's classes for a better compatibility with Deesse interface. We should first sort it out and then we'll think about hosting the mpstool in pypi.

I'll keep you in a loop!

**Comment by GCoiffier** [comment]
Please note that Julien's work has already been partially adapted in the `Image` class, and on the `pointset-block-data` branch, but it is still a WIP. I'd be glad if someone could finish it.

**Comment by pjuda** [comment]
Yes, thanks, that's a good step forward :)
